feat: copy process from hm-pktfwd
NebraLtd/sx1302_hal pull request #1
Opened 2021-10-18 16:52 UTC by marvinmarnold

**Why**
The hm-pktfwd build process is confusing. Instead of building lora_gateway, packet_forwarder, and sx1302_hal in a single Dockerfile, this is being broken up into a Dockerfile per repo.

This will remain a draft until testing is complete in [hm-pktfwd](https://github.com/NebraLtd/hm-pktfwd/tree/marvinmarnold/total-refactor-2).

**How**
- Deleted unnecessary files and copied in modified versions where needed. 
- Did not copy test_loragw_gps.c or test_loragw_gps_i2c.c because loragw_gps.c is [not being used](https://github.com/NebraLtd/hm-pktfwd/issues/23#issuecomment-906254260).

**References**
- Related to: https://github.com/NebraLtd/lora_gateway/pull/2
- Related to: https://github.com/NebraLtd/packet_forwarder/pull/2
- Related to: https://github.com/NebraLtd/hm-pktfwd/pull/59

2021-10-20 22:58 UTC, shawaj commented on packet_forwarder/src/lora_pkt_fwd.c
> +//            printf("### Concentrator temperature unknown ###\n");
Guessing we could actually leave these in... Although maybe no point as it would obviously always print 30 degrees. So maybe no point

2021-10-20 22:58 UTC, shawaj commented on packet_forwarder/src/lora_pkt_fwd.c
>  #endif
We should add the chip version string here too potentially?

As per...
https://github.com/Lora-net/sx1302_hal/pull/60/files

2021-10-20 22:59 UTC, shawaj commented
> Did not copy test_loragw_gps.c or test_loragw_gps_i2c.c because loragw_gps.c is not being used

We may need to add these back in again in the future with our updated sx1303 based concentrator but not necessary for now as we don't use the GPS currently

2021-10-21 01:24 UTC, shawaj requested changes

2021-10-21 01:24 UTC, shawaj commented on tools/reset_lgw.sh
> +fi
This won't work as the script calling is built into the hal 

https://github.com/NebraLtd/sx1302_hal/blob/3d73e6af43535f700ff7b6c2b49cc79d388cd70f/packet_forwarder/src/lora_pkt_fwd.c#L1656-L1662

This is why we were using `sed`

2021-10-21 19:15 UTC, marvinmarnold commented on tools/reset_lgw.sh
> +fi
Good catch. How about [this](https://github.com/NebraLtd/sx1302_hal/pull/1/commits/bea966a2e9de142742248e5e9d94d59174fd9d33#diff-bd5477175815818c1a48d879d7debc4d6c882e762a8715872cf2f193371a6065R15) behavior?

Not much different but lets you use env var or command arg to set the pin.

2021-10-21 19:22 UTC, marvinmarnold commented on packet_forwarder/src/lora_pkt_fwd.c
> +//            printf("### Concentrator temperature unknown ###\n");
Its a pet peeve of mine that the concentrator is so noisy in the logs. How about we use [MSG_DEBUG](https://github.com/NebraLtd/sx1302_hal/pull/1/commits/6324b7a568ee24dbd9c4da64df69169a22615311#diff-8285781ad70868e8f8ac3dfc6bbba4b99f218308479f53abccdd015592b99ad7R1892) so that the verbosity can be controlled? I'm not in love with that though because you have to rebuild in order to change the msg level.

2021-10-21 20:18 UTC, shawaj commented on packet_forwarder/src/lora_pkt_fwd.c
>  #endif
Yeah I just mean to add in the diff for lora_pkt_fwd.c from https://github.com/Lora-net/sx1302_hal/pull/60/files so when starting the concentrator we have a chip model ID output printed to logs:
```
#include "loragw_aux.h"
#include "loragw_reg.h"
#include "loragw_gps.h"
#include "loragw_sx1302.h"

/* -------------------------------------------------------------------------- */
/* --- PRIVATE MACROS ------------------------------------------------------- */
@@ -1482,6 +1483,7 @@ int main(int argc, char ** argv)
    uint32_t inst_tstamp;
    uint64_t eui;
    float temperature;
    sx1302_model_id_t model_id;

    /* statistics variable */
    time_t t;
@@ -1670,6 +1672,14 @@ int main(int argc, char ** argv)
        printf("INFO: concentrator EUI: 0x%016" PRIx64 "\n", eui);
    }

    /* get the concentrator chip model */
    i = sx1302_get_model_id(&model_id);
    if (i != LGW_HAL_SUCCESS) {
        printf("ERROR: failed to get concentrator chip model\n");
    } else {
        printf("INFO: concentrator chip model ID: 0x%02X\n", model_id);
    }
```

2021-10-22 23:45 UTC, merged